# Generated by Django 4.0.3 on 2024-02-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(default='4', max_length=300),
            preserve_default=False,
        ),
    ]
